b_users/models.py
from flask_login import UserMixin
from extension import database


class User(database.Model, UserMixin):
    __tablename__ = 'user'
    id = database.Column(database.Integer, primary_key = True)
    first_name = database.Column(database.String(30), nullable = False)
    last_name = database.Column(database.String(50), nullable = False)
    email_id = database.Column(database.String(30),nullable = False, unique = True)
    password = database.Column(database.String(30), nullable = False)
    country = database.Column(database.String(50), nullable=True)

b_users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, EmailField, SelectField
from wtforms.validators import InputRequired, Length, ValidationError
from .models import User
from .utils import fetch_all_countries


class SignupForm(FlaskForm):
    first_name = StringField(validators=[InputRequired(), Length(min=3, max=30)], render_kw={"placeholder": "First Name"})
    last_name = StringField(validators=[InputRequired(), Length(min=3, max=30)], render_kw={"placeholder": "Last Name"})
    email_id = EmailField(validators=[InputRequired(), Length(min=4, max=30)], render_kw={"placeholder": "Email Id"})
    password = PasswordField(validators=[InputRequired(), Length(min=3, max=30)], render_kw={"placeholder": "Password"})
    country = SelectField('country', choices=fetch_all_countries(), render_kw={"id": "country", "class": "form-control"}) 


class SigninForm(FlaskForm):
    email_id = EmailField(validators=[InputRequired(), Length(min=4, max=30)], render_kw={"placeholder": "Email Id"})
    password = PasswordField(validators=[InputRequired(), Length(min=3, max=30)], render_kw={"placeholder": "Password"})
    
    
class UserForm(FlaskForm):
    first_name = StringField(validators=[InputRequired(), Length(min=3, max=30)], render_kw={"placeholder": "First Name"})
    last_name = StringField(validators=[InputRequired(), Length(min=3, max=30)], render_kw={"placeholder": "Last Name"})
    email_id = EmailField(validators=[InputRequired(), Length(min=4, max=30)], render_kw={"placeholder": "Email Id"})
    country = SelectField('country', choices=fetch_all_countries(), render_kw={"id": "country", "class": "form-control"}) 

b_users/__init__.py
from flask import Blueprint


users_bp = Blueprint("users", __name__, template_folder="templates")

from b_users import routes

b_users/routes.py
from b_users import users_bp
from flask import render_template, request, redirect, url_for
from .models import User
from .forms import SigninForm, SignupForm, UserForm
from .utils import fetch_all_countries
from extension import database, bcrypt, login_man
from flask_login import login_user, logout_user, current_user, login_required, LoginManager

@users_bp.route("/home")
@users_bp.route("/")
def home():
    return render_template('home.html')

@users_bp.route("/aboutus")
def aboutus():
    return render_template('aboutus.html')

@users_bp.route("/signup", methods=['GET', 'POST'])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        encrypt_password = bcrypt.generate_password_hash(form.password.data)
        user = User(first_name = form.first_name.data, last_name = form.last_name.data, email_id = form.email_id.data, password = encrypt_password, country=form.country.data)
        database.session.add(user)
        database.session.commit()
        return redirect(url_for('users.signin'))
    return render_template('signup.html', form=form)


@users_bp.route("/signin", methods=['GET', 'POST'])
def signin():
    form = SigninForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email_id=form.email_id.data).first()
        if user:
            if bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for('users.home'))
    return render_template('login.html', form=form)


@users_bp.route("/logout", methods=['GET', 'POST'])
def logout():
    logout_user()
    return redirect(url_for('users.signin'))

@login_man.user_loader
def userload(id):
    return User.query.get(int(id))


@users_bp.route("/profile", methods=['GET', 'POST'])
def profile():
    user = User.query.get(current_user.id)
    form = UserForm(obj=user)

    if form.validate_on_submit():
        form.populate_obj(user)
        database.session.commit()
    return render_template('profile.html', form=form)

b_users/templates/_partials/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="static/css/style.css"/> -->
    <link rel="stylesheet" href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' />
    <link rel="stylesheet" href='https://unicons.iconscout.com/release/v4.0.0/css/line.css' />

    <title>BlogoSphere</title>
    <link
            rel="icon"
            href=
"static/img/13442522861553771544-128.png"
            type="image/x-icon"
        />
  </head>
  <body >
    {% include 'includes/header.html' %}
    <div class="d-flex flex-column min-vh-100">
    {% block body %}

    {% endblock %}
      <div class="container flex-grow-1">
      </div>
      <footer class="text-center text-white mt-auto" style="background-color: #15253F;">
  {% include 'includes/footer.html' %}
    </footer>
</div>
    
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </body>
</html>

b_users/templates/aboutus.html
{% extends '_partials/base.html' %}

{% block title %}
<title> Blogging System</title>
{% endblock %}

{% block body %}
<section class="py-3 py-md-5 py-xl-8">
    <div class="container">
      <div class="row">
        <div class="col-12 col-md-10 col-lg-8">
          <h3 class="fs-5 mb-2 text-secondary text-uppercase">Share. Inspire. Connect. Explore.</h3>
          <h2 class="display-5 mb-4">Dive into a community where your stories spark conversations and your insights ignite change.</h2>
          <button type="button" style="background: #9f0630" class="btn btn-lg mb-3 mb-md-4 mb-xl-5 text-white">Connect Now</button>
        </div>
      </div>
    </div>
  
    <div class="container">
      <div class="row gy-3 gy-md-4 gy-lg-0">
        <div class="col-12 col-lg-6">
          <div class="card bg-light p-3 m-0">
            <div class="row gy-3 gy-md-0 align-items-md-center">
              <div class="col-md-5">
                <img src="static/img/lifestyle1.jpg" class="img-fluid rounded-start" alt="Why Choose Us?">
              </div>
              <div class="col-md-7">
                <div class="card-body p-0">
                  <h2 class="card-title h4 mb-3">Why Choose Us?</h2>
                  <p class="card-text lead">With years of experience and deep industry knowledge, we have a proven track record of success and are pushing ourselves to stay ahead of the curve.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-12 col-lg-6">
          <div class="card bg-light p-3 m-0">
            <div class="row gy-3 gy-md-0 align-items-md-center">
              <div class="col-md-5">
                <img src="static/img/Lifestyle.jpg" class="img-fluid rounded-start" alt="Visionary Team">
              </div>
              <div class="col-md-7">
                <div class="card-body p-0">
                  <h2 class="card-title h4 mb-3">Visionary Team</h2>
                  <p class="card-text lead">With a team of visionary engineers, developers, and creative minds, we embark on a journey to transform complex challenges into ingenious technological solutions.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

b_users/templates/home.html
{% extends '_partials/base.html' %}

{% block title %}
<title> Blogging System</title>
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-12 col-lg-6">
            <div class="column">
                <h1 class="mbr-section-title mbr-fonts-style mb-5 display-1"><strong>Voice Vision Venture Vibrance</strong></h1>
            
            <p class="mbr-text mbr-fonts-style display-7">
                Rise Above The Noise To Connect With Your and other's Thoughts.</p>
          <div class="mbr-section-btn mt-5"><a  style="background-color: #9f0630;" class="btn btn-lg mb-3 mb-md-4 mb-xl-5 display-2 text-white" href="#"><span>Let’s Talk!</span></a></div>
            </div>      
               
        </div>
        <div class="col-22 col-lg-6 mb-3 mb-md-4 mb-xl-5">
            <div class="column">
            
            <!-- <p class="mbr-text mbr-fonts-style display-7"> -->
                <img src="static/img/home1.jpg"
                class="img-fluid" alt="Sample image"></p>
            </div>                
        </div>
    </div>
</div>
<div class="container">
<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="mbr-section-head">
            <!-- <h3 class="mbr-section-title mbr-fonts-style align-center display-2">CATEGORIES</h3> -->
            
        </div>
    </div>
    <div class="col-md-3 col-lg-4 col-md-12">
        <!-- mbr-fonts-style align-center mb-3  -->
        <div class="card">
            <!-- <h4 class="mbr-section-subtitle mbr-fonts-style align-center mb-3 mt-3 display-7">01</h4> -->
            <h3 class="mbr-section-title text-center">LIFESTYLE </h3>
            <img src="static\img\lifestyle2.jpg" alt="Mobirise Website Builder">
            
           <a  style="background-color: #71989B;" class="btn btn-lg display-2" href="#"><span>Check this</span></a>
        </div>

    </div>
    <div class="col-md-3 col-lg-4 col-md-12">

        <div class="card">
            <!-- <h4 class="mbr-section-subtitle mbr-fonts-style align-center mb-3 mt-3 display-7">02</h4> -->
            <h3 class="mbr-section-title text-center">TECHNOLOGY</h3> 
            <img src="static/img/technology.jpg" alt="Mobirise Website Builder">
        <a  style="background-color: #71989B;" class="btn btn-lg display-2" href="#"><span>Check this</span></a>
        </div>

    </div>
    <div class="col-md-3 col-lg-4 col-md-12">

        <div class="card">
            <!-- <h4 class="mbr-section-subtitle mbr-fonts-style align-center mb-3 mt-3 display-7">03</h4> -->
            <h3 class="mbr-section-title text-center">EDUCATION AND CAREER</h3>
            <img src="static/img/educationandcareer.jpg" alt="Mobirise Website Builder">
            <!-- <p class="mbr-section-text mbr-fonts-style align-center mb-0 mt-4 display-7"> -->
            
           <a  style="background-color: #71989B;" class="btn btn-lg display-2" href="#"><span>Check this</span></a>
        </div>

    </div>
</div>
</div>
<div class="container">
    <BR>
    <BR>
    <BR>

</div>
{% endblock %}

b_users/templates/includes/footer.html
    <!--footer-->
    <script src="https://kit.fontawesome.com/e5b8e80481.js" crossorigin="anonymous"></script>
    <footer class=" text-center text-white mt-auto " style="background-color: #9f0630;">
      <!-- Grid container -->
      <div class="container p-4 pb-0">
        <!-- Section: Social media -->
        <section class="mb-4">
          <!-- Facebook -->
          <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button" 
            ><i class="fab fa-facebook-f"></i
          ></a>
    
          <!-- Twitter -->
          <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
            ><i class="fab fa-twitter"></i
          ></a>
    
          <!-- Google -->
          <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
            ><i class="fab fa-google"></i
          ></a>
    
          <!-- Instagram -->
          <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
            ><i class="fab fa-instagram"></i
          ></a>
    
          <!-- Linkedin -->
          <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
            ><i class="fab fa-linkedin-in"></i
          ></a>
    
          <!-- Github -->
          <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
            ><i class="fab fa-github"></i
          ></a>
        </section>
        <!-- Section: Social media -->
      </div>
      <!-- Grid container -->
    
      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2023 Copyright:
        <a class="text-white" href="" >BlogoSphere.com</a>
      </div>
      <!-- Copyright -->
    </footer>

b_users/templates/includes/header.html
<link href="https://fonts.googleapis.com/css?family=Schoolbell&v1" rel="stylesheet">
<style>
  ul {
  text-align: center;
}

ul a {
  transition: 0.3s ease;
  /* background: #9f0630; */
  color: #9f0630;
  font-size: 20px;
  text-decoration: none;
  border-top: 4px solid transparent;
  border-bottom: 4px solid transparent;
  padding: 20px 0;
  margin: 0 5px;
  font-size: 17px;
}
ul a:hover {
  border-top: 4px solid #9f0630;
  border-bottom: 4px solid #9f0630;
  padding: 6px 0; 
}
</style>
<div>
  <header class="blog-header py-3 p-3" style="background:#E4960E;">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <!-- <a class="text-muted" href="#">Subscribe</a> -->
        <!-- <a class="blog-header-logo text-dark" style="font-family: 'Lucida Calligraphy', Lucida Calligraphy, serif;font-size: 40px;" href="#">Jingaa</a> -->

      </div>
      <div class="col-4 text-center">
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Ephesis&display=swap');
        </style>
        <a class="blog-header-logo " style="font-family: serif;font-size: 40px; color: #0e1517  ;" href="#">BlogoSphere</a>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="text-muted" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
        </a>
        <!-- <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a> -->
      </div>
    </div>
  </header>
  <header class="d-flex align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom p-3">
    <a href="/" class="d-flex align-items-center col-md-2 mb-2 mb-md-0 text-dark text-decoration-none">
    </a>

    <ul style="font-size: 20px;" class="nav col-12 col-md-auto mb-7 justify-content-center mb-md-0">
      <li><a href="{{ url_for('users.home') }}" class="nav-link px-2 link-dark" >Home</a></li>
      {% if current_user.is_authenticated %}
      <li><a href="{{ url_for('blogs.blogs') }}" class="nav-link px-2 link-dark">Blogs</a></li>
      <li><a href="{{ url_for('blogs.my_blogs') }}" class="nav-link px-2 link-dark">My Blogs</a></li>
      <li><a href="{{ url_for('blogs.news_articles') }}" class="nav-link px-2 link-dark">News Articles</a></li>
      <li><a href="{{ url_for('blogs.blog_videos') }}" class="nav-link px-2 link-dark">Blogging Videos</a></li>
      <li><a href="{{ url_for('users.profile') }}" class="nav-link px-2 link-dark">Profile</a></li>
      
      {% endif %}
      <li><a href="{{ url_for('users.aboutus') }}" class="nav-link px-2 link-dark">About Us</a></li>
    </ul>

    <div class="col-md-3 ">
      {% if current_user.is_authenticated %}
      <a href="{{ url_for('users.logout') }}"><button type="button"  class="btn me-2" style="background-color: #71989B;">Logout</button></a>
      {% endif %}

      {% if not current_user.is_authenticated %}
      <a href="{{ url_for('users.signin') }}"><button type="button"  class="btn me-2" style="background-color: #71989B;">Login</button></a>   

      <a href="{{ url_for('users.signup') }}"><button type="button" class="btn text-dark" style="background-color: #71989B;">Sign-up</button></a>
      {% endif %}
    </div>
  </header>
</div>

b_users/templates/login.html
{% extends '_partials/base.html' %}


{% block body %}
<div class="d-flex justify-content-center">
    <form method="POST" action="{{ url_for('users.signin') }}">
      {{ form.hidden_tag() }}
        <div class="row mb-4">
          <label for="inputEmail3" class="col-sm-4 col-form-label">Email</label>
          <div class="col-sm-10">
            {{ form.email_id(class_="form-control") }}
          </div>
        </div>
        <div class="row mb-4">
          <label for="inputPassword3" class="col-sm-4 col-form-label">Password</label>
          <div class="col-sm-10">
            {{ form.password(class_="form-control") }}
          </div>
        </div>
        <button type="submit" style="background-color: #9f0630;" class="btn text-white">Sign in</button>
      </form>
</div>
<br>

{% endblock %}

b_users/templates/profile.html
{% extends '_partials/base.html' %}

{% block body %}

<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                    <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">User Profile</p>
  
                  <form class="mx-1 mx-md-4" method="post" action="{{ url_for('users.profile') }}">
                   {{ form.hidden_tag() }}
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        {{ form.first_name(class_="form-control") }}
                      </div>
                    </div>

                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        {{ form.last_name(class_="form-control") }}
                      </div>
                    </div>

                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        {{ form.country() }}
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        {{ form.email_id(class_="form-control") }}
                      </div>
                    </div>
  
                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <button type="submit" class="btn btn-primary btn-lg">Update Details</button>
                    </div>
  
                  </form>
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  {% endblock %}

b_users/templates/signup.html
{% extends '_partials/base.html' %}

{% block body %}

<section class="vh-100" style="background-color: #eee;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>

                <form class="mx-1 mx-md-4" method="post" action="{{ url_for('users.signup') }}">
                  {{ form.hidden_tag() }}
                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      {{ form.first_name(class_="form-control") }}
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      {{ form.last_name(class_="form-control") }}
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      {{ form.country() }}
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      {{ form.email_id(class_="form-control") }}
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      {{ form.password(class_="form-control") }}
                    </div>
                  </div>

                  <div class="form-check d-flex justify-content-center mb-5">
                    <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3c" />
                    <label class="form-check-label" for="form2Example3">
                      I agree all statements in <a href="#!">Terms of service</a>
                    </label>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" class="btn btn-primary btn-lg">Register</button>
                  </div>

                </form>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

b_users/templates/users.html
<h1>users Page</h1>